export const capData = [
  {
    capId: "CAP-1000",
    issueClusterId: "CL-1521",
    rootCauseCategory: "Posting Delay",
    capAction: "Implement auto-posting validation rules",
    estimatedRecovery: 42383.69,
    capStatus: "Planned" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 1",
    targetCompletionDate: "8/31/2024",
    confidenceScore: 0.75,
    narrativeSummary:
      "Cluster CL-1521 shows Posting Delay with potential risk score of 0.62.",
    capDescription:
      "Issue Cluster CL-1521 is linked to the root cause 'Posting Delay'. The CAP action 'Implement auto-posting validation rules' is expected to recover $42,383.69. Assigned to Audit Team 1, the action aims to resolve audit weaknesses and is currently marked as 'Planned'.",
  },
  {
    capId: "CAP-1001",
    issueClusterId: "CL-1737",
    rootCauseCategory: "Posting Delay",
    capAction: "Add missing backup document training",
    estimatedRecovery: 114780.57,
    capStatus: "Planned" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 1",
    targetCompletionDate: "9/30/2024",
    confidenceScore: 0.75,
    narrativeSummary:
      "Cluster CL-1737 shows Posting Delay with potential risk score of 0.36.",
    capDescription:
      "Issue Cluster CL-1737 is linked to the root cause 'Posting Delay'. The CAP action 'Add missing backup document training' is expected to recover $114,780.57. Assigned to Audit Team 1, the action aims to resolve audit weaknesses and is currently marked as 'Implemented'.",
  },
  {
    capId: "CAP-1002",
    issueClusterId: "CL-1740",
    rootCauseCategory: "Posting Delay",
    capAction: "Update disbursement reconciliation protocol",
    estimatedRecovery: 47778.68,
    capStatus: "In Progress" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 2",
    targetCompletionDate: "10/31/2024",
    confidenceScore: 0.75,
    narrativeSummary:
      "Cluster CL-1740 shows Posting Delay with potential risk score of 0.35.",
    capDescription:
      "Issue Cluster CL-1740 is linked to the root cause 'Posting Delay'. The CAP action 'Update disbursement reconciliation protocol' is expected to recover $47,778.68. Assigned to Audit Team 2, the action aims to resolve audit weaknesses and is currently marked as 'Pending Review'.",
  },
  {
    capId: "CAP-1003",
    issueClusterId: "CL-1660",
    rootCauseCategory: "Missing Backup",
    capAction: "Enhance posting delay alerts",
    estimatedRecovery: 113482.11,
    capStatus: "Implemented" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 1",
    targetCompletionDate: "11/30/2024",
    confidenceScore: 0.82,
    narrativeSummary:
      "Cluster CL-1660 shows Missing Backup with potential risk score of 0.34.",
    capDescription:
      "Issue Cluster CL-1660 is linked to the root cause 'Missing Backup'. The CAP action 'Enhance posting delay alerts' is expected to recover $113,482.11. Assigned to Audit Team 1, the action aims to resolve audit weaknesses and is currently marked as 'Planned'.",
  },
  {
    capId: "CAP-1004",
    issueClusterId: "CL-1411",
    rootCauseCategory: "Posting Delay",
    capAction: "Correct SLOA mismatch process",
    estimatedRecovery: 119319.55,
    capStatus: "Implemented" as const,
    remediationPriority: "High" as const,
    nfrIssued: true,
    auditOwnerGroup: "Audit Team 2",
    targetCompletionDate: "12/31/2024",
    confidenceScore: 0.69,
    narrativeSummary:
      "Cluster CL-1411 shows Posting Delay with potential risk score of 0.62.",
    capDescription:
      "Issue Cluster CL-1411 is linked to the root cause 'Posting Delay'. The CAP action 'Correct SLOA mismatch process' is expected to recover $119,319.55. Assigned to Audit Team 2, the action aims to resolve audit weaknesses and is currently marked as 'In Progress'.",
  },
  {
    capId: "CAP-1005",
    issueClusterId: "CL-1678",
    rootCauseCategory: "Posting Delay",
    capAction: "Introduce monthly issue review board",
    estimatedRecovery: 128187.92,
    capStatus: "Planned" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 3",
    targetCompletionDate: "1/31/2025",
    confidenceScore: 0.76,
    narrativeSummary:
      "Cluster CL-1678 shows Posting Delay with potential risk score of 0.34.",
    capDescription:
      "Issue Cluster CL-1678 is linked to the root cause 'Posting Delay'. The CAP action 'Introduce monthly issue review board' is expected to recover $128,187.92. Assigned to Audit Team 3, the action aims to resolve audit weaknesses and is currently marked as 'Implemented'.",
  },
  {
    capId: "CAP-1006",
    issueClusterId: "CL-1626",
    rootCauseCategory: "Posting Delay",
    capAction: "Deploy document audit bot",
    estimatedRecovery: 60940.23,
    capStatus: "Implemented" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: true,
    auditOwnerGroup: "Audit Team 1",
    targetCompletionDate: "2/28/2025",
    confidenceScore: 0.74,
    narrativeSummary:
      "Cluster CL-1626 shows Posting Delay with potential risk score of 0.36.",
    capDescription:
      "Issue Cluster CL-1626 is linked to the root cause 'Posting Delay'. The CAP action 'Deploy document audit bot' is expected to recover $60,940.23. Assigned to Audit Team 1, the action aims to resolve audit weaknesses and is currently marked as 'In Progress'.",
  },
  {
    capId: "CAP-1007",
    issueClusterId: "CL-1513",
    rootCauseCategory: "Posting Delay",
    capAction: "Review upstream feeder integration",
    estimatedRecovery: 147537.39,
    capStatus: "In Progress" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 2",
    targetCompletionDate: "3/31/2025",
    confidenceScore: 0.83,
    narrativeSummary:
      "Cluster CL-1513 shows Posting Delay with potential risk score of 0.36.",
    capDescription:
      "Issue Cluster CL-1513 is linked to the root cause 'Posting Delay'. The CAP action 'Review upstream feeder integration' is expected to recover $147,537.39. Assigned to Audit Team 2, the action aims to resolve audit weaknesses and is currently marked as 'In Progress'.",
  },
  {
    capId: "CAP-1008",
    issueClusterId: "CL-1859",
    rootCauseCategory: "Posting Delay",
    capAction: "Tighten JV approval workflow",
    estimatedRecovery: 122853.74,
    capStatus: "Planned" as const,
    remediationPriority: "Medium" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 2",
    targetCompletionDate: "4/30/2025",
    confidenceScore: 0.82,
    narrativeSummary:
      "Cluster CL-1859 shows Posting Delay with potential risk score of 0.35.",
    capDescription:
      "Issue Cluster CL-1859 is linked to the root cause 'Posting Delay'. The CAP action 'Tighten JV approval workflow' is expected to recover $122,853.74. Assigned to Audit Team 2, the action aims to resolve audit weaknesses and is currently marked as 'Planned'.",
  },
  {
    capId: "CAP-1009",
    issueClusterId: "CL-1136",
    rootCauseCategory: "Missing Backup",
    capAction: "Establish exception tracking mechanism",
    estimatedRecovery: 15609.98,
    capStatus: "Pending Review" as const,
    remediationPriority: "Low" as const,
    nfrIssued: false,
    auditOwnerGroup: "Audit Team 3",
    targetCompletionDate: "5/31/2025",
    confidenceScore: 0.9,
    narrativeSummary:
      "Cluster CL-1136 shows Missing Backup with potential risk score of 0.32.",
    capDescription:
      "Issue Cluster CL-1136 is linked to the root cause 'Missing Backup'. The CAP action 'Establish exception tracking mechanism' is expected to recover $15,609.98. Assigned to Audit Team 3, the action aims to resolve audit weaknesses and is currently marked as 'Implemented'.",
  },
];
